### ISSUE TITLE
Update to Cake 0.30.0

### ISSUE THREAD

**Issue by skovsende** [cake-contrib/Cake.ProGet#1]
To remove warnings when used in Cake 0.30.0

**Comment by gep13** [comment]
@skovsende nice!  Looks like you got access to the repository.  Let me know if you have any questions.

Can you let me know the best email address to get you on (perhaps via Gitter DM) so I can invite you to a Slack Team.  Also, are you on Twitter?

**Comment by gep13** [comment]
@skovsende also, regarding this...

Assuming you are not using anything that specifically shipped in 0.30.0, you would probably be best to use 0.28.0, since there are no breaking changes between 0.28.0 and 0.30.0, so that would mean that this addin could be used by more people, i.e. those still using 0.28.0.
